### ISSUE TITLE
File name is failed

### ISSUE THREAD

**Issue by jeuxjeux20** [XeZrunner/WebcamViewer#6]
https://github.com/XeZrunner/WebcamViewer/releases

> wv-overviewy

overview**y**

**Comment by XeZrunner** [comment]
I understand this causes confusion, as the source code hasn't been synced for a long time now, and I've only released the final executables recently, but the name _overview**y**_ is intentional.

It's a joke codename for an in-development feature: If the experiment is enabled in the Settings -> Debug settings, it enables 2 extra buttons in the menu, which let you choose between the classic list-style and a more modern, tile-looking overview with previews style. The feature is a very early "copy-paste" of the Overview page, hence the codename _overview**y**_.

Perhaps I shouldn't have put it up as a non-preview release, but the latest release was a bit older than what the actual latest code had to offer.

**Comment by jeuxjeux20** [comment]
why isn't thius close deeeeeeeeeeee
